name: Check Rust
on:
  pull_request:

# stop in-progress on new push
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - name: Check-Out
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nightly
        run: |
          rustup toolchain install nightly
          rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt

      - name: cargo +nightly fmt
        run: cargo +nightly fmt --all -- --check

  cargo-check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
      - name: Check-Out
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: cargo check --workspace --all-features
        run: cargo check --workspace --all-features

  cargo-clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - name: Check-Out
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: cargo clippy --workspace --all-features
        run: cargo clippy --workspace --all-features

  cargo-fix:
    name: cargo fix
    runs-on: ubuntu-latest
    steps:
      - name: Check-Out
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: Swatinem/rust-cache@v2

      - name: cargo fix --workspace --all-features
        run: |
          # Run cargo fix on the project
          cargo fix --workspace --all-features

          # Check for local git changes
          if ! git diff --exit-code; then
              echo "There are local changes after running 'cargo fix --workspace --all-features' ❌"
              exit 1
          else
              echo "No changes detected after running 'cargo fix --workspace --all-features' ✅"
          fi

  cargo-test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Check-Out
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: cargo test --workspace
        run: cargo test --workspace

  cargo-audit:
    name: cargo audit
    runs-on: ubuntu-latest
    steps:
      - name: Check-Out
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Utilize Shared Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: cargo-audit
          cache-on-failure: true

      - name: Install cargo-audit
        run: cargo install --force cargo-audit

      - name: cargo audit
        run: |
          cargo audit
